name: "pySHiELD translate tests"
on:
  pull_request:

jobs:
  pyshield_translate_tests:
    uses:  NOAA-GFDL/PySHiELD/.github/workflows/translate.yaml@develop
    with:
      component_trigger: true
      component_name: pyFV3
