name: "Translate pyFV3 test (subset)"
on:
  workflow_call:
    inputs:
      component_trigger:
        type:  boolean
        default: false
        required: false
      component_name:
        type: string
        default: 'None'
        required: false
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pyFV3_translate_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noaa-gfdl/miniforge:mpich
    steps:

      - name: Checkout pyFV3 for externally triggered
        if: ${{inputs.component_trigger}}
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          repository:  noaa-gfdl/pyFV3
          path: pyFV3

      - name: Checkout NDSL for externally triggered
        if: ${{inputs.component_trigger}}
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          path: pyFV3/${{inputs.component_name}}

      - name: Checkout pyFV3 for interally triggered
        if: ${{ ! inputs.component_trigger }}
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          path: pyFV3
